blockExoticSubdeps: true
enablePrePostScripts: false
ignorePatchFailures: false
minimumReleaseAge: 1440
optimisticRepeatInstall: true
resolutionMode: 'lowest-direct'
trustPolicy: 'no-downgrade'
trustPolicyIgnoreAfter: 10080
verifyDepsBeforeRun: 'install'
